# Copyright © 2010 Fazlul Shahriar <fshahriar@gmail.com>.
# See LICENSE file for license details.

include $(GOROOT)/src/Make.inc

TARG=go-netrc.googlecode.com/hg/netrc
GOFILES=\
	netrc.go\

include $(GOROOT)/src/Make.pkg
